Only warn if pom.xml is found
SonarSource/sonarcloud-github-action pull request #29
Opened 2021-08-23 19:19 UTC by andreas-kind

See: https://community.sonarsource.com/t/maven-project-detected-you-should-run-the-goal-org-sonarsource-scanner-maven-sonar-during-build-rather-than-using-this-github-action/36158

2021-10-12 13:20 UTC, workshur commented
You can use this https://github.com/SonarSource/sonarcloud-github-action/pull/19

2022-08-15 08:39 UTC, tom-vanbraband-sonarsource requested changes
Hi! Thanks for you contribution, in the majority of cases we don't want to use the sonarcloud-github-action if a project has a pom.xml. In those cases we want to make sure the user knows they are not getting the most out of their analysis, and we want them to use the Maven scanner.

Therefore I don't think it makes sense to output just a warning.

What would make sense is to add a flag which can override the failure, something like `IGNORE_MAVEN`

2024-03-14 08:32 UTC, sasa-fajkovic commented
I agree with @tom-vanbraband-sonarsource  as the documentation of the GHA mentions to not use this GHA for Maven projects (and some other scenarios). The script should break to enforce prevention of usage of this GHA

2024-04-17 15:22 UTC, 7PH commented
Hi @andreas-kind , I will go ahead and close this PR for cleanup as it's been more than a year without activity. A new PR could still be opened with @tom-vanbraband-sonarsource 's suggested resolution.

2024-04-17 15:22 UTC, closed without merging